import {zColor} from "@remotion/zod-types";
import {z} from "zod";
import {defineTemplateManifest} from "../../../packages/template-sdk/src";
export const mediaGridSchema = z.object({title: z.string().max(36), asset1: z.string(), label1: z.string().max(18), asset2: z.string(), label2: z.string().max(18), asset3: z.string(), label3: z.string().max(18), asset4: z.string(), label4: z.string().max(18), gridCount: z.union([z.literal(2), z.literal(3), z.literal(4)]), accentColor: zColor(), stylePreset: z.enum(["editorial", "minimal", "vibrant"])});
export type MediaGridProps = z.infer<typeof mediaGridSchema>;
export const mediaGridManifest = defineTemplateManifest<MediaGridProps>({
  id: "media-grid", compositionId: "MediaGrid", version: "1.0.0", name: "多宫格素材对比", category: "media", tags: ["宫格", "对比", "多图", "分屏"], description: "支持 2、3、4 宫格图片或视频对比与标签。", schema: mediaGridSchema,
  defaultProps: {title: "方案对比", asset1: "", label1: "方案 A", asset2: "", label2: "方案 B", asset3: "", label3: "方案 C", asset4: "", label4: "方案 D", gridCount: 2, accentColor: "#47A7FF", stylePreset: "editorial"},
  fields: [{key: "title", label: "标题", section: "content", control: "text", maxLength: 36}, {key: "gridCount", label: "宫格数量", section: "layout", control: "select", options: [{label: "2 宫格", value: 2}, {label: "3 宫格", value: 3}, {label: "4 宫格", value: 4}]}, {key: "asset1", label: "素材 1", section: "data", control: "media", accept: ["image", "video"]}, {key: "label1", label: "标签 1", section: "data", control: "text", maxLength: 18}, {key: "asset2", label: "素材 2", section: "data", control: "media", accept: ["image", "video"]}, {key: "label2", label: "标签 2", section: "data", control: "text", maxLength: 18}, {key: "asset3", label: "素材 3", section: "data", control: "media", accept: ["image", "video"]}, {key: "label3", label: "标签 3", section: "data", control: "text", maxLength: 18}, {key: "asset4", label: "素材 4", section: "data", control: "media", accept: ["image", "video"]}, {key: "label4", label: "标签 4", section: "data", control: "text", maxLength: 18}, {key: "stylePreset", label: "样式预设", section: "style", control: "select", options: [{label: "编辑部", value: "editorial"}, {label: "极简边框", value: "minimal"}, {label: "强对比", value: "vibrant"}]}, {key: "accentColor", label: "强调色", section: "style", control: "color"}], durationMode: "fixed-edges", capabilities: {alpha: true, audio: false, mediaSlots: 4, minDurationFrames: 90, maxDurationFrames: 18_000, supportedAspectRatios: ["16:9", "9:16", "1:1", "custom"]}, stylePresets: [{id: "editorial", name: "编辑部", patch: {stylePreset: "editorial"}}, {id: "minimal", name: "极简边框", patch: {stylePreset: "minimal"}}, {id: "vibrant", name: "强对比", patch: {stylePreset: "vibrant"}}], migrations: [], preview: {accent: "#47A7FF", label: "2 × 2"},
});
