import {zColor} from "@remotion/zod-types";
import {z} from "zod";
import {defineTemplateManifest} from "../../../packages/template-sdk/src";

/* eslint-disable @remotion/non-pure-animation -- “transition” is a serialized template field name, not a CSS animation. */

export const mediaCarouselSchema = z.object({title: z.string().max(36), asset1: z.string(), label1: z.string().max(24), asset2: z.string(), label2: z.string().max(24), asset3: z.string(), label3: z.string().max(24), asset4: z.string(), label4: z.string().max(24), asset5: z.string(), label5: z.string().max(24), itemCount: z.number().int().min(2).max(5), transition: z.enum(["slide", "cut", "crossfade"]), accentColor: zColor(), stylePreset: z.enum(["editorial", "minimal", "vibrant"])});
export type MediaCarouselProps = z.infer<typeof mediaCarouselSchema>;
export const mediaCarouselManifest = defineTemplateManifest<MediaCarouselProps>({id: "media-carousel", compositionId: "MediaCarousel", version: "1.0.0", name: "素材轮播序列", category: "media", tags: ["轮播", "图片", "视频", "序列"], description: "按时长自动分页轮播最多五段图片或视频素材。", schema: mediaCarouselSchema, defaultProps: {title: "现场记录", asset1: "", label1: "01 · 入口", asset2: "", label2: "02 · 中庭", asset3: "", label3: "03 · 展厅", asset4: "", label4: "04 · 屋顶", asset5: "", label5: "05 · 夜景", itemCount: 3, transition: "slide", accentColor: "#47A7FF", stylePreset: "editorial"}, fields: [{key: "title", label: "标题", section: "content", control: "text", maxLength: 36}, {key: "itemCount", label: "素材数量", section: "layout", control: "number", min: 2, max: 5, step: 1}, {key: "transition", label: "切换方式", section: "animation", control: "select", options: [{label: "滑动", value: "slide"}, {label: "硬切", value: "cut"}, {label: "交叉淡化", value: "crossfade"}]}, {key: "asset1", label: "素材 1", section: "data", control: "media", accept: ["image", "video"], required: true}, {key: "label1", label: "标签 1", section: "data", control: "text", maxLength: 24}, {key: "asset2", label: "素材 2", section: "data", control: "media", accept: ["image", "video"], required: true}, {key: "label2", label: "标签 2", section: "data", control: "text", maxLength: 24}, {key: "asset3", label: "素材 3", section: "data", control: "media", accept: ["image", "video"], required: false}, {key: "label3", label: "标签 3", section: "data", control: "text", maxLength: 24}, {key: "asset4", label: "素材 4", section: "data", control: "media", accept: ["image", "video"], required: false}, {key: "label4", label: "标签 4", section: "data", control: "text", maxLength: 24}, {key: "asset5", label: "素材 5", section: "data", control: "media", accept: ["image", "video"], required: false}, {key: "label5", label: "标签 5", section: "data", control: "text", maxLength: 24}, {key: "stylePreset", label: "样式", section: "style", control: "select", options: [{label: "编辑部", value: "editorial"}, {label: "极简", value: "minimal"}, {label: "鲜明", value: "vibrant"}]}, {key: "accentColor", label: "强调色", section: "style", control: "color"}], durationMode: "paginate", capabilities: {alpha: true, audio: false, mediaSlots: 5, minDurationFrames: 120, maxDurationFrames: 18_000, maxItems: 5, supportedAspectRatios: ["16:9", "9:16", "1:1", "custom"]}, stylePresets: [{id: "editorial", name: "编辑部", patch: {stylePreset: "editorial"}}, {id: "minimal", name: "极简", patch: {stylePreset: "minimal"}}, {id: "vibrant", name: "鲜明", patch: {stylePreset: "vibrant"}}], migrations: [], preview: {accent: "#47A7FF", label: "01  02  03"}});
