import {zColor} from "@remotion/zod-types";
import {z} from "zod";
import {defineTemplateManifest} from "../../../packages/template-sdk/src";
export const mediaInfoSchema = z.object({assetId: z.string(), title: z.string().min(1).max(40), body: z.string().max(140), source: z.string().max(56), layout: z.enum(["media-left", "media-right", "media-full"]), mediaFit: z.enum(["cover", "contain", "fill"]), focalX: z.number().min(0).max(100), focalY: z.number().min(0).max(100), mediaScale: z.number().min(0.5).max(2), mediaRadius: z.number().min(0).max(120), videoInSeconds: z.number().min(0).max(3600), videoOutSeconds: z.number().min(0).max(3600), playbackRate: z.number().min(0.25).max(4), playbackMode: z.enum(["once", "loop", "hold"]), accentColor: zColor(), stylePreset: z.enum(["editorial", "minimal", "vibrant"])});
export type MediaInfoProps = z.infer<typeof mediaInfoSchema>;
export const mediaInfoManifest = defineTemplateManifest<MediaInfoProps>({
  id: "media-info", compositionId: "MediaInfo", version: "1.2.0", name: "素材文字信息卡", category: "media", tags: ["图片", "视频", "信息卡", "图文"], description: "将图片或视频与标题、正文组合成透明信息卡。", schema: mediaInfoSchema,
  defaultProps: {assetId: "", title: "城市更新计划", body: "老厂房被改造为开放式文化空间，在保留工业肌理的同时引入公共艺术与社区活动。", source: "现场拍摄", layout: "media-left", mediaFit: "cover", focalX: 50, focalY: 50, mediaScale: 1, mediaRadius: 0, videoInSeconds: 0, videoOutSeconds: 0, playbackRate: 1, playbackMode: "hold", accentColor: "#47A7FF", stylePreset: "editorial"},
  fields: [{key: "assetId", label: "图片 / 视频", section: "data", control: "media", accept: ["image", "video"], required: true}, {key: "title", label: "标题", section: "content", control: "text", maxLength: 40}, {key: "body", label: "正文", section: "content", control: "textarea", maxLength: 140, rows: 4}, {key: "source", label: "来源", section: "source", control: "text", maxLength: 56}, {key: "layout", label: "图文布局", section: "layout", control: "select", options: [{label: "素材在左", value: "media-left"}, {label: "素材在右", value: "media-right"}, {label: "全幅素材", value: "media-full"}]}, {key: "mediaFit", label: "素材适配", section: "layout", control: "select", options: [{label: "Fill 填充", value: "cover"}, {label: "Fit 完整显示", value: "contain"}, {label: "Stretch 拉伸", value: "fill"}]}, {key: "focalX", label: "焦点 X（%）", section: "layout", control: "number", min: 0, max: 100, step: 1}, {key: "focalY", label: "焦点 Y（%）", section: "layout", control: "number", min: 0, max: 100, step: 1}, {key: "mediaScale", label: "素材缩放", section: "layout", control: "number", min: 0.5, max: 2, step: 0.05}, {key: "mediaRadius", label: "素材圆角", section: "style", control: "number", min: 0, max: 120, step: 2}, {key: "videoInSeconds", label: "视频入点（秒）", section: "animation", control: "number", min: 0, max: 3600, step: 0.1}, {key: "videoOutSeconds", label: "视频出点（秒，0 为不限）", section: "animation", control: "number", min: 0, max: 3600, step: 0.1}, {key: "playbackRate", label: "播放速度", section: "animation", control: "number", min: 0.25, max: 4, step: 0.05}, {key: "playbackMode", label: "片段结束后", section: "animation", control: "select", options: [{label: "定格尾帧", value: "hold"}, {label: "循环播放", value: "loop"}, {label: "隐藏素材", value: "once"}]}, {key: "stylePreset", label: "样式预设", section: "style", control: "select", options: [{label: "编辑部", value: "editorial"}, {label: "极简", value: "minimal"}, {label: "杂志", value: "vibrant"}]}, {key: "accentColor", label: "强调色", section: "style", control: "color"}], durationMode: "fixed-edges", capabilities: {alpha: true, audio: false, mediaSlots: 1, minDurationFrames: 90, maxDurationFrames: 18_000, supportedAspectRatios: ["16:9", "9:16", "1:1", "custom"]}, stylePresets: [{id: "editorial", name: "编辑部", patch: {stylePreset: "editorial"}}, {id: "minimal", name: "极简", patch: {stylePreset: "minimal"}}, {id: "vibrant", name: "杂志", patch: {stylePreset: "vibrant", accentColor: "#FF6B9A"}}], migrations: [{from: "1.0.0", to: "1.1.0", migrate: (props) => ({...props as object, mediaFit: "cover", focalX: 50, focalY: 50, mediaScale: 1, mediaRadius: 0, videoInSeconds: 0}) as MediaInfoProps}, {from: "1.1.0", to: "1.2.0", migrate: (props) => mediaInfoSchema.parse({...props as object, videoOutSeconds: 0, playbackRate: 1, playbackMode: "hold"})}], preview: {accent: "#FF6B9A", label: "MEDIA + TEXT"},
});
