import {zColor} from "@remotion/zod-types";
import {z} from "zod";
import {defineTemplateManifest} from "../../../packages/template-sdk/src";
export const milestoneSchema = z.object({date: z.string().max(16), title: z.string().min(1).max(28), description: z.string().max(64)});
export const timelineSchema = z.object({title: z.string().min(1).max(36), items: z.array(milestoneSchema).min(1).max(8), source: z.string().max(56), accentColor: zColor(), stylePreset: z.enum(["editorial", "minimal", "vibrant"])});
export type TimelineProps = z.infer<typeof timelineSchema>;
export const timelineManifest = defineTemplateManifest<TimelineProps>({
  id: "timeline", compositionId: "Timeline", version: "1.0.0", name: "时间线里程碑", category: "information", tags: ["时间线", "历史", "里程碑", "事件"], description: "按时间顺序展示关键事件，数据较多时自动分页。", schema: timelineSchema,
  defaultProps: {title: "产品发展历程", items: [{date: "2022", title: "项目启动", description: "完成概念验证"}, {date: "2023", title: "首次发布", description: "正式投入生产"}, {date: "2024", title: "全球扩展", description: "覆盖 12 个市场"}, {date: "2026", title: "新一代产品", description: "进入智能创作阶段"}], source: "公司资料", accentColor: "#47A7FF", stylePreset: "editorial"},
  fields: [{key: "title", label: "标题", section: "content", control: "text", maxLength: 36}, {key: "items", label: "里程碑", section: "data", control: "data-array", columns: [{key: "date", label: "日期", kind: "text", width: 0.7}, {key: "title", label: "事件", kind: "text"}, {key: "description", label: "说明", kind: "text", width: 1.3}], minItems: 1, maxItems: 8, newItem: {date: "2026", title: "新事件", description: "补充说明"}}, {key: "source", label: "来源", section: "source", control: "text", maxLength: 56}, {key: "stylePreset", label: "样式预设", section: "style", control: "select", options: [{label: "档案", value: "editorial"}, {label: "极简线", value: "minimal"}, {label: "发布会", value: "vibrant"}]}, {key: "accentColor", label: "强调色", section: "style", control: "color"}], durationMode: "paginate", capabilities: {alpha: true, audio: false, mediaSlots: 0, minDurationFrames: 120, maxDurationFrames: 18_000, maxItems: 8, supportedAspectRatios: ["16:9", "9:16", "1:1", "custom"]}, stylePresets: [{id: "editorial", name: "档案", patch: {stylePreset: "editorial"}}, {id: "minimal", name: "极简线", patch: {stylePreset: "minimal"}}, {id: "vibrant", name: "发布会", patch: {stylePreset: "vibrant"}}], migrations: [], preview: {accent: "#47A7FF", label: "2022 → 2026"},
});
