import {zColor} from "@remotion/zod-types";
import {z} from "zod";
import {defineTemplateManifest} from "../../../packages/template-sdk/src";
import {rankingItemSchema} from "../horizontal-ranking/manifest";
export const verticalBarsSchema = z.object({title: z.string().min(1).max(36), items: z.array(rankingItemSchema).min(1).max(8), source: z.string().max(56), showAxis: z.boolean(), accentColor: zColor(), stylePreset: z.enum(["editorial", "minimal", "vibrant"])});
export type VerticalBarsProps = z.infer<typeof verticalBarsSchema>;
export const verticalBarsManifest = defineTemplateManifest<VerticalBarsProps>({
  id: "vertical-bars", compositionId: "VerticalBars", version: "1.0.0", name: "纵向柱状图", category: "chart", tags: ["柱状图", "类目", "比较"], description: "适合比较 1–8 个离散类目，可显示坐标网格。", schema: verticalBarsSchema,
  defaultProps: {title: "月度新增用户", items: [{label: "1月", value: 42, color: "#47A7FF"}, {label: "2月", value: 61, color: "#47A7FF"}, {label: "3月", value: 54, color: "#47A7FF"}, {label: "4月", value: 78, color: "#47A7FF"}, {label: "5月", value: 92, color: "#47A7FF"}], source: "运营数据", showAxis: true, accentColor: "#47A7FF", stylePreset: "editorial"},
  fields: [{key: "title", label: "标题", section: "content", control: "text", maxLength: 36}, {key: "items", label: "柱状数据", section: "data", control: "data-array", columns: [{key: "label", label: "类目", kind: "text"}, {key: "value", label: "数值", kind: "number"}, {key: "color", label: "颜色", kind: "color", width: 0.55}], minItems: 1, maxItems: 8, newItem: {label: "新类目", value: 50, color: "#47A7FF"}}, {key: "showAxis", label: "显示坐标网格", section: "layout", control: "boolean"}, {key: "source", label: "来源", section: "source", control: "text", maxLength: 56}, {key: "stylePreset", label: "样式预设", section: "style", control: "select", options: [{label: "新闻数据", value: "editorial"}, {label: "极简", value: "minimal"}, {label: "高对比", value: "vibrant"}]}, {key: "accentColor", label: "强调色", section: "style", control: "color"}], durationMode: "stretch", capabilities: {alpha: true, audio: false, mediaSlots: 0, minDurationFrames: 90, maxDurationFrames: 18_000, maxItems: 8, supportedAspectRatios: ["16:9", "9:16", "1:1", "custom"]}, stylePresets: [{id: "editorial", name: "新闻数据", patch: {stylePreset: "editorial"}}, {id: "minimal", name: "极简", patch: {stylePreset: "minimal"}}, {id: "vibrant", name: "高对比", patch: {stylePreset: "vibrant"}}], migrations: [], preview: {accent: "#47A7FF", label: "▂▅▄▇█"},
});
