import {zColor} from "@remotion/zod-types";
import {z} from "zod";
import {defineTemplateManifest} from "../../../packages/template-sdk/src";
export const sourceCardSchema = z.object({title: z.string().min(1).max(48), summary: z.string().max(180), author: z.string().max(28), organization: z.string().max(36), date: z.string().max(20), source: z.string().max(80), url: z.string().max(240), accessDate: z.string().max(20), displayMode: z.enum(["short", "full"]), accentColor: zColor(), stylePreset: z.enum(["editorial", "minimal", "vibrant"])});
export type SourceCardProps = z.infer<typeof sourceCardSchema>;
export const sourceCardManifest = defineTemplateManifest<SourceCardProps>({
  id: "source-card", compositionId: "SourceCard", version: "1.1.0", name: "资料来源卡", category: "information", tags: ["资料", "来源", "摘要", "引用"], description: "呈现文献、报告或新闻资料的标题与出处。", schema: sourceCardSchema,
  defaultProps: {title: "全球能源转型年度报告", summary: "报告梳理了清洁能源投资、区域进展与未来五年的关键趋势。", author: "研究中心", organization: "国际能源观察", date: "2026.08", source: "示例资料 / 第 42 页", url: "https://example.com/report", accessDate: "2026.08.09", displayMode: "short", accentColor: "#47A7FF", stylePreset: "editorial"},
  fields: [{key: "title", label: "资料标题", section: "content", control: "text", maxLength: 48}, {key: "summary", label: "摘要", section: "content", control: "textarea", maxLength: 180, rows: 4}, {key: "author", label: "作者", section: "source", control: "text", maxLength: 28}, {key: "organization", label: "机构", section: "source", control: "text", maxLength: 36}, {key: "date", label: "发布日期", section: "source", control: "text", maxLength: 20}, {key: "source", label: "出处 / 文章", section: "source", control: "text", maxLength: 80}, {key: "url", label: "网址", section: "source", control: "text", maxLength: 240}, {key: "accessDate", label: "访问日期", section: "source", control: "text", maxLength: 20}, {key: "displayMode", label: "画面出处", section: "source", control: "select", options: [{label: "简短机构名", value: "short"}, {label: "完整脚注", value: "full"}]}, {key: "stylePreset", label: "样式预设", section: "style", control: "select", options: [{label: "编辑部", value: "editorial"}, {label: "极简卡片", value: "minimal"}, {label: "重点标记", value: "vibrant"}]}, {key: "accentColor", label: "强调色", section: "style", control: "color"}], durationMode: "fixed-edges", capabilities: {alpha: true, audio: false, mediaSlots: 0, minDurationFrames: 90, maxDurationFrames: 18_000, supportedAspectRatios: ["16:9", "9:16", "1:1", "custom"]}, stylePresets: [{id: "editorial", name: "编辑部", patch: {stylePreset: "editorial"}}, {id: "minimal", name: "极简卡片", patch: {stylePreset: "minimal"}}, {id: "vibrant", name: "重点标记", patch: {stylePreset: "vibrant", accentColor: "#FFCC4A"}}], migrations: [{from: "1.0.0", to: "1.1.0", migrate: (props) => sourceCardSchema.parse({...props as object, url: "", accessDate: "", displayMode: "short"})}], preview: {accent: "#FFCC4A", label: "SOURCE"},
});
