import {zColor} from "@remotion/zod-types";
import {z} from "zod";
import {defineTemplateManifest} from "../../../packages/template-sdk/src";
import {rankingItemSchema} from "../horizontal-ranking/manifest";
export const donutShareSchema = z.object({title: z.string().min(1).max(36), centerLabel: z.string().max(16), items: z.array(rankingItemSchema).min(1).max(6), source: z.string().max(56), accentColor: zColor(), stylePreset: z.enum(["editorial", "minimal", "vibrant"])});
export type DonutShareProps = z.infer<typeof donutShareSchema>;
export const donutShareManifest = defineTemplateManifest<DonutShareProps>({
  id: "donut-share", compositionId: "DonutShare", version: "1.0.0", name: "环形占比图", category: "chart", tags: ["环形", "占比", "份额"], description: "显示最多六个类目的结构占比与中心文案。", schema: donutShareSchema,
  defaultProps: {title: "市场份额", centerLabel: "总计 100%", items: [{label: "品牌 A", value: 42, color: "#47A7FF"}, {label: "品牌 B", value: 28, color: "#73D2DE"}, {label: "品牌 C", value: 18, color: "#9B8AFB"}, {label: "其他", value: 12, color: "#5A6470"}], source: "行业调研", accentColor: "#47A7FF", stylePreset: "editorial"},
  fields: [{key: "title", label: "标题", section: "content", control: "text", maxLength: 36}, {key: "centerLabel", label: "中心文案", section: "content", control: "text", maxLength: 16}, {key: "items", label: "占比数据", section: "data", control: "data-array", columns: [{key: "label", label: "类目", kind: "text"}, {key: "value", label: "数值", kind: "number"}, {key: "color", label: "颜色", kind: "color", width: 0.55}], minItems: 1, maxItems: 6, newItem: {label: "新类目", value: 10, color: "#47A7FF"}}, {key: "source", label: "来源", section: "source", control: "text", maxLength: 56}, {key: "stylePreset", label: "样式预设", section: "style", control: "select", options: [{label: "新闻数据", value: "editorial"}, {label: "极简", value: "minimal"}, {label: "鲜明", value: "vibrant"}]}, {key: "accentColor", label: "强调色", section: "style", control: "color"}], durationMode: "stretch", capabilities: {alpha: true, audio: false, mediaSlots: 0, minDurationFrames: 90, maxDurationFrames: 18_000, maxItems: 6, supportedAspectRatios: ["16:9", "9:16", "1:1", "custom"]}, stylePresets: [{id: "editorial", name: "新闻数据", patch: {stylePreset: "editorial"}}, {id: "minimal", name: "极简", patch: {stylePreset: "minimal"}}, {id: "vibrant", name: "鲜明", patch: {stylePreset: "vibrant"}}], migrations: [], preview: {accent: "#9B8AFB", label: "42%"},
});
